services:
  db:
    image: pgvector/pgvector:pg16
    container_name: investochat-db
    restart: always
    env_file: .env.db
    ports:
      - "5432:5432"
    volumes:
      - ./data/db:/var/lib/postgresql/data

  adminer:
    image: adminer
    container_name: investochat-adminer
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db